export const TRUCK_TYPES = [
  "Panel Van",
  "Bakkie",
  "Bakkie with canopy",
  "Small Dropside",
  "Small Flatbed",
  "Refrigerated Van",
  "Box Body Rigid",
  "Curtainside Rigid",
  "Dropside Rigid",
  "Flatbed Rigid",
  "Refrigerated Rigid",
  "Tipper Rigid",
  "Tanker Rigid",
  "Logging Rigid",
  "Car Carrier Rigid",
  "Livestock Rigid",
  "Flatbed Semi",
  "Curtainside Semi",
  "Box Semi",
  "Refrigerated Semi",
  "Lowbed Semi",
  "Tipper Semi",
  "Tanker Semi",
  "Container Trailer (Skeletal)",
  "Side Lifter Semi",
  "Livestock Semi",
  "Car Carrier Semi",
  "Logging Semi",
  "Flatbed Interlink",
  "Curtainside Interlink",
  "Box Interlink",
  "Refrigerated Interlink",
  "Lowbed Interlink",
  "Tipper Interlink",
  "Tanker Interlink",
  "Container Interlink (skeletal)",
  "Livestock Interlink",
  "Car Carrier Interlink",
  "Logging Interlink",
] as const;

export type TruckType = (typeof TRUCK_TYPES)[number];
